### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by forteller** [livarb/turbo-chrome-ext#18]
Now that Firefox use the same webExtension system as Chrome it should not be too hard to make a Firefox version. Hope you can do that. Thanks!

**Comment by livarb** [comment]
Only needed to add permissions in the manifest for fetching data from my server and from hotell.difi.no when on data.norge.no. Seems to work well. I'll publish it as a Firefox extension for testing.

**Comment by livarb** [comment]
Submitted to Firefox Add-ons:
https://addons.mozilla.org/en-US/firefox/addon/turbo-tillegg-for-data-norge/

**Comment by forteller** [comment]
Awesome!

**Comment by livarb** [comment]
Firefox-plugin is out and seems to be working fine.
